---
kind: Service
apiVersion: v1
metadata:
  name: writer
spec:
  selector:
    app: writer
  type: NodePort
  ports:
  - port: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: writer
  labels:
    app: writer
spec:
  template:
    metadata:
      labels:
        app: writer
    spec:
      containers:
      - image: redisrabbitmqwriter:latest
        name: writer
        imagePullPolicy: Never #to receive image from local repo
        env:
          - name: REDIS_HOSTNAME
            value: redis
          - name: REDIS_PORT
            value: "6379"
          - name: RABBIT_MQ_HOSTNAME
            value: rabbitmq
          - name: RABBIT_MQ_PORT
            value: "5672"
          - name: REDIS_QUEUE_NAME
            value: "env_queue"
        ports:
        - containerPort: 80